[project]
name = "videojungle-agent-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.114.0",
    "mcp>=1.6.0",
    "mcpadapt>=0.1.3",
    "video-editor-mcp>=0.1.16",
]
